from fastapi import APIRouter
from typing import List

router = APIRouter(prefix="/api/countries", tags=["Countries"])

# Comprehensive list of countries
COUNTRIES = [
    {"code": "IT", "name": "Italy"},
    {"code": "DE", "name": "Germany"},
    {"code": "FR", "name": "France"},
    {"code": "ES", "name": "Spain"},
    {"code": "NL", "name": "Netherlands"},
    {"code": "BE", "name": "Belgium"},
    {"code": "AT", "name": "Austria"},
    {"code": "CH", "name": "Switzerland"},
    {"code": "GB", "name": "United Kingdom"},
    {"code": "IE", "name": "Ireland"},
    {"code": "PT", "name": "Portugal"},
    {"code": "GR", "name": "Greece"},
    {"code": "PL", "name": "Poland"},
    {"code": "CZ", "name": "Czech Republic"},
    {"code": "HU", "name": "Hungary"},
    {"code": "SK", "name": "Slovakia"},
    {"code": "SI", "name": "Slovenia"},
    {"code": "HR", "name": "Croatia"},
    {"code": "RO", "name": "Romania"},
    {"code": "BG", "name": "Bulgaria"},
    {"code": "EE", "name": "Estonia"},
    {"code": "LV", "name": "Latvia"},
    {"code": "LT", "name": "Lithuania"},
    {"code": "FI", "name": "Finland"},
    {"code": "SE", "name": "Sweden"},
    {"code": "NO", "name": "Norway"},
    {"code": "DK", "name": "Denmark"},
    {"code": "US", "name": "United States"},
    {"code": "CA", "name": "Canada"},
    {"code": "AU", "name": "Australia"},
    {"code": "NZ", "name": "New Zealand"},
    {"code": "JP", "name": "Japan"},
    {"code": "KR", "name": "South Korea"},
    {"code": "CN", "name": "China"},
    {"code": "IN", "name": "India"},
    {"code": "BR", "name": "Brazil"},
    {"code": "AR", "name": "Argentina"},
    {"code": "MX", "name": "Mexico"},
    {"code": "RU", "name": "Russia"},
    {"code": "TR", "name": "Turkey"},
    {"code": "ZA", "name": "South Africa"},
    {"code": "EG", "name": "Egypt"},
    {"code": "MA", "name": "Morocco"},
    {"code": "NG", "name": "Nigeria"},
    {"code": "KE", "name": "Kenya"},
    {"code": "GH", "name": "Ghana"},
    {"code": "ET", "name": "Ethiopia"},
    {"code": "TZ", "name": "Tanzania"},
    {"code": "UG", "name": "Uganda"},
    {"code": "RW", "name": "Rwanda"},
    {"code": "SN", "name": "Senegal"},
    {"code": "CI", "name": "Ivory Coast"},
    {"code": "ML", "name": "Mali"},
    {"code": "BF", "name": "Burkina Faso"},
    {"code": "NE", "name": "Niger"},
    {"code": "TD", "name": "Chad"},
    {"code": "CM", "name": "Cameroon"},
    {"code": "CF", "name": "Central African Republic"},
    {"code": "CD", "name": "Democratic Republic of the Congo"},
    {"code": "CG", "name": "Republic of the Congo"},
    {"code": "GA", "name": "Gabon"},
    {"code": "GQ", "name": "Equatorial Guinea"},
    {"code": "ST", "name": "São Tomé and Príncipe"},
    {"code": "AO", "name": "Angola"},
    {"code": "ZM", "name": "Zambia"},
    {"code": "ZW", "name": "Zimbabwe"},
    {"code": "BW", "name": "Botswana"},
    {"code": "NA", "name": "Namibia"},
    {"code": "SZ", "name": "Eswatini"},
    {"code": "LS", "name": "Lesotho"},
    {"code": "MG", "name": "Madagascar"},
    {"code": "MU", "name": "Mauritius"},
    {"code": "SC", "name": "Seychelles"},
    {"code": "KM", "name": "Comoros"},
    {"code": "DJ", "name": "Djibouti"},
    {"code": "SO", "name": "Somalia"},
    {"code": "ER", "name": "Eritrea"},
    {"code": "SD", "name": "Sudan"},
    {"code": "SS", "name": "South Sudan"},
    {"code": "LY", "name": "Libya"},
    {"code": "TN", "name": "Tunisia"},
    {"code": "DZ", "name": "Algeria"},
    {"code": "MR", "name": "Mauritania"},
    {"code": "ML", "name": "Mali"},
    {"code": "BF", "name": "Burkina Faso"},
    {"code": "NE", "name": "Niger"},
    {"code": "TD", "name": "Chad"},
    {"code": "CM", "name": "Cameroon"},
    {"code": "CF", "name": "Central African Republic"},
    {"code": "CD", "name": "Democratic Republic of the Congo"},
    {"code": "CG", "name": "Republic of the Congo"},
    {"code": "GA", "name": "Gabon"},
    {"code": "GQ", "name": "Equatorial Guinea"},
    {"code": "ST", "name": "São Tomé and Príncipe"},
    {"code": "AO", "name": "Angola"},
    {"code": "ZM", "name": "Zambia"},
    {"code": "ZW", "name": "Zimbabwe"},
    {"code": "BW", "name": "Botswana"},
    {"code": "NA", "name": "Namibia"},
    {"code": "SZ", "name": "Eswatini"},
    {"code": "LS", "name": "Lesotho"},
    {"code": "MG", "name": "Madagascar"},
    {"code": "MU", "name": "Mauritius"},
    {"code": "SC", "name": "Seychelles"},
    {"code": "KM", "name": "Comoros"},
    {"code": "DJ", "name": "Djibouti"},
    {"code": "SO", "name": "Somalia"},
    {"code": "ER", "name": "Eritrea"},
    {"code": "SD", "name": "Sudan"},
    {"code": "SS", "name": "South Sudan"},
    {"code": "LY", "name": "Libya"},
    {"code": "TN", "name": "Tunisia"},
    {"code": "DZ", "name": "Algeria"},
    {"code": "MR", "name": "Mauritania"},
    {"code": "OTHER", "name": "Other"}
]

@router.get("", response_model=List[dict])
async def list_countries():
    """Get list of all available countries."""
    return COUNTRIES

@router.get("/{country_code}")
async def get_country(country_code: str):
    """Get a specific country by code."""
    country = next((c for c in COUNTRIES if c["code"].upper() == country_code.upper()), None)
    if not country:
        return {"error": "Country not found"}
    return country
